import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next Pizza | Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (    
    <main className="min-h-screen">
      DASHBOARD HEADER
      {children}
    </main>
  );
}
